keys:
  - &user age14z79rakkhfe3eupz8t9nj7ajxt9hts2jfaa38a0jkup5k04tt4nqnlvfh6
  - &server age1x7sxqu5msy20mm3wx2t9yfafhxz6tzrttzgjcllydrhm0phsxe6q7w7l93
  - &agent age152qrwa29qvfljlff7m9pec25wm5am2lftywc0fjttdnyq8chss5qvzqdku
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user
          - *server
          - *agent
